server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Necessário para o roteamento do Angular funcionar corretamente
        try_files $uri $uri/ /index.html;
    }
}
